---
- name: Check running jobs on MongoDB cluster 
  mdb_deploy: 
    cluster: "{{ group }}" 
    user:    "{{ user }}" 
    key:     "{{ key }}" 
    mms:     "{{ mms }}" 
    verify:  "{{ no_verify | default(verify) }}"
  delegate_to: localhost
  register: result
  failed_when: result.meta != 1

- debug: msg={{ result.meta }}
